# Site
name: 'kevinboosten.dev'
title: 'Kevin Boosten Blog'
description: 'Just writing about front-end development'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'UA-77121716-4'
disqus: kevinboosten
mailchimp-list:
include: ['_pages']
permalink: /:title

# Authors
authors:
  kevin:
    name: Kevin
    display_name: Kevin Boosten
    gravatar: ae009796c3ab12724e416d3a2dad9046
    email: kevinboosten@icloud.com
    web: https://kevinboosten.nl
    twitter: https://twitter.com/kevinboosten
    github: https://github.com/kevinboosten
    devto: https://dev.to/kevinboosten
    description: 'Front-end developer with a love for Ionic and Firebase'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: 'disabled'

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
